[features]
seeds = false
skip-lint = false
[programs.localnet]
transfer_sol = "DZe1TcbWUcY2ftLZJ9BXT695VBLYj9deE4N2NkGh25oP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/praky/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
